name: Deploy via git-ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: git FTP PUSH
      run: |
      apt-get install git-ftp -y
      git pull --recurse-submodules
      git ftp push -u ${{ secrets.FTP_USER }} -p ${{ secrets.FTP_PASSWORD }} -f -v --syncroot "." "ftp://ftp.federicocapece.com/www.federicocapece.com/api/q2anotificationsbot"
