on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftp.federicocapece.com
        FTP_USERNAME: 7782710@aruba.it
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        REMOTE_DIR:  /www.federicocapece.com/api/q2anotificationsbot
        ARGS: --delete
        # --delete arg will delete files on the server if you've deleted them in git
